version: "3.9"
services:
  db:
    image: postgres:14-alpine
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apiDB
    ports:
      - "5434:5432"
    networks:
      - db-net

  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - db-net

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - db-net

networks:
  db-net:
